const companies = [
    "Reliance Industries Limited",
    "TCS",
    "HDFC Bank",
    "ICICI Bank",
    "HUL",
    "Infosys",
    "ITC",
    "SBI",
    "Bharti Airtel",
    "Bajaj Finance",
    "LIC India",
    "Larsen & Toubro",
    "Kotak Mahindra",
    "Asian Paints",
    "HCL Tech",
    "Axis Bank",
    "Adani Enterprises",
    "Maruti Suzuki",
    "Sun Pharma",
    "Titan Company",
    "Avenue Supermart",
    "Bajaj Finserv",
    "UltraTech Cement",
    "ONGC",
    "Nestle",
    "Wipro",
    "NTPC",
    "Tata Motors",
    "JSW Steel",
    "M&M",
    "Power Grid Corporation of India",
    "Adani Ports",
    "Adani Green Enterprise",
    "LTIMindtree",
    "Tata Steel",
    "Coal India",
    "HDFC Life",
    "Siemens",
    "Hindustan Zinc",
    "Bajaj Auto",
    "Pidilite Ind",
    "IOC",
    "Britannia",
    "Tech Mahindra",
    "IndusInd Bank",
    "Adani Power",
    "Varun Beverages",
    "Godrej Consumer",
    "Hindalco",
    "Dabur India",
    "Divis Labs",
    "Bank of Baroda",
    "Cipla",
    "Interglobe Avi",
    "Dr Reddys Labs",
    "ABB India",
    "Ambuja Cements",
    "Bharat Elec",
    "Eicher Motors",
    "Vedanta",
    "Chola Invest",
    "Adani Trans",
    "Shree Cements",
    "SBI Card",
    "ICICI Prudentia",
    "Havells India",
    "Zomato",
    "Bajaj Holdings",
    "BPCL",
    "TATA Cons. Prod",
    "GAIL",
    "Mankind Pharma",
    "Tata Power",
    "Marico",
    "United Spirits",
    "Apollo Hospital",
    "Adani Total Gas",
    "Torrent Pharma",
    "Polycab",
    "Shriram Finance",
    "IDBI Bank",
    "Berger Paints",
    "Power Finance",
    "Macrotech Dev",
    "SRF",
    "ICICI Lombard",
    "Jindal Steel",
    "PNB",
    "Zydus Life",
    "MOTHERSON",
    "TVS Motor",
    "Info Edge",
    "CG Power",
    "Trent",
    "Union Bank",
    "Tube Investment",
    "MRF",
    "Hero MotoCorp",
    "ONE 97 COMMUNICATIONS",
    "JK Tyre & Industries Ltd."
];

module.exports = companies;